#!/usr/bin/env bash
# 在已有 smelt-signal 的 Ubuntu（腾讯云等）上安装 coturn，并写入 SMELT_ICE_SERVERS。
#
# 用法（上机 root / sudo）：
#   PUBLIC_IP=1.2.3.4 DOMAIN=signal.example.com bash install-coturn.sh
#   # DOMAIN 可省略（用 IP 作 realm，ICE urls 用 IP）
#   PUBLIC_IP=1.2.3.4 bash install-coturn.sh
#
# 环境变量：
#   PUBLIC_IP   必填，弹性公网 IP
#   DOMAIN      可选，有则 ICE 用域名（stun:/turn:DOMAIN:3478）
#   TURN_USER   默认 smelt
#   TURN_PASS   默认随机生成并打印一次
#   RELAY_MIN / RELAY_MAX  默认 49152 / 49251
#   SKIP_SIGNAL_ENV=1  只装 coturn，不改 smelt-signal 环境
set -euo pipefail

log() { echo "[$(date +%H:%M:%S)] $*"; }
die() { echo "✗ $*" >&2; exit 1; }

[[ "$(id -u)" -eq 0 ]] || die "请用 sudo / root 运行"

PUBLIC_IP="${PUBLIC_IP:-}"
DOMAIN="${DOMAIN:-}"
TURN_USER="${TURN_USER:-smelt}"
TURN_PASS="${TURN_PASS:-}"
RELAY_MIN="${RELAY_MIN:-49152}"
RELAY_MAX="${RELAY_MAX:-49251}"
SKIP_SIGNAL_ENV="${SKIP_SIGNAL_ENV:-0}"

[[ -n "$PUBLIC_IP" ]] || die "请设置 PUBLIC_IP=你的弹性公网IP"

if [[ -z "$TURN_PASS" ]]; then
  TURN_PASS="$(openssl rand -base64 24 | tr -d '/+=' | head -c 24)"
  GENERATED_PASS=1
else
  GENERATED_PASS=0
fi

if [[ -n "$DOMAIN" ]]; then
  ICE_HOST="$DOMAIN"
  REALM="$DOMAIN"
else
  ICE_HOST="$PUBLIC_IP"
  REALM="smelt-turn"
fi

log ">>> 1/5 安装 coturn"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq coturn

log ">>> 2/5 写 /etc/turnserver.conf"
cat >/etc/turnserver.conf <<EOF
# generated by install-coturn.sh $(date -u +%Y-%m-%dT%H:%MZ)
listening-ip=0.0.0.0
listening-port=3478
fingerprint
lt-cred-mech
user=${TURN_USER}:${TURN_PASS}
realm=${REALM}
external-ip=${PUBLIC_IP}
min-port=${RELAY_MIN}
max-port=${RELAY_MAX}
no-cli
no-multicast-peers
no-loopback-peers
simple-log
EOF

# Ubuntu 包默认 TURNSERVER_ENABLED=0
if [[ -f /etc/default/coturn ]]; then
  sed -i 's/^#*TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/default/coturn
  grep -q '^TURNSERVER_ENABLED=1' /etc/default/coturn || echo 'TURNSERVER_ENABLED=1' >>/etc/default/coturn
fi

log ">>> 3/5 启动 coturn"
systemctl enable coturn 2>/dev/null || systemctl enable turnserver 2>/dev/null || true
if systemctl list-unit-files | grep -q '^coturn\.service'; then
  systemctl restart coturn
  systemctl --no-pager --full status coturn | head -15 || true
elif systemctl list-unit-files | grep -q '^turnserver\.service'; then
  systemctl restart turnserver
  systemctl --no-pager --full status turnserver | head -15 || true
else
  die "找不到 coturn/turnserver systemd unit"
fi

if [[ "$SKIP_SIGNAL_ENV" != "1" ]]; then
  log ">>> 4/5 写入 smelt-signal SMELT_ICE_SERVERS"
  mkdir -p /etc/smelt
  ENV_FILE=/etc/smelt/smelt-signal.env
  touch "$ENV_FILE"
  # 公共 STUN + 本机 TURN（JSON 单行，无空格，方便 EnvironmentFile）
  ICE_JSON=$(cat <<JSON
[{"urls":"stun:${ICE_HOST}:3478"},{"urls":["turn:${ICE_HOST}:3478?transport=udp","turn:${ICE_HOST}:3478?transport=tcp"],"username":"${TURN_USER}","credential":"${TURN_PASS}"},{"urls":"stun:stun.qq.com:3478"},{"urls":"stun:stun.miwifi.com:3478"},{"urls":"stun:stun.cloudflare.com:3478"},{"urls":"stun:stun.l.google.com:19302"}]
JSON
)
  # 去掉换行
  ICE_JSON="$(echo "$ICE_JSON" | tr -d '\n')"

  if grep -q '^SMELT_ICE_SERVERS=' "$ENV_FILE" 2>/dev/null; then
    # 用临时文件替换该行（避免 sed 与 JSON 引号搏斗）
    grep -v '^SMELT_ICE_SERVERS=' "$ENV_FILE" >"${ENV_FILE}.tmp" || true
    mv "${ENV_FILE}.tmp" "$ENV_FILE"
  fi
  printf 'SMELT_ICE_SERVERS=%s\n' "$ICE_JSON" >>"$ENV_FILE"

  if systemctl is-enabled smelt-signal &>/dev/null || systemctl is-active smelt-signal &>/dev/null; then
    systemctl restart smelt-signal
    log "smelt-signal 已 restart"
  else
    log "未检测到 smelt-signal.service，请自行 restart 并确保 EnvironmentFile 含 SMELT_ICE_SERVERS"
  fi
else
  log ">>> 4/5 SKIP_SIGNAL_ENV=1，跳过信号环境"
fi

log ">>> 5/5 完成"
echo
echo "======== 保存以下信息 ========"
echo "TURN user:     $TURN_USER"
if [[ "$GENERATED_PASS" == "1" ]]; then
  echo "TURN password: $TURN_PASS   ← 仅此一次打印，请存密码管理器"
else
  echo "TURN password: (你提供的 TURN_PASS)"
fi
echo "ICE host:      $ICE_HOST"
echo "Relay ports:   UDP ${RELAY_MIN}-${RELAY_MAX}"
echo
echo "腾讯云安全组请放行："
echo "  UDP+TCP 3478"
echo "  UDP ${RELAY_MIN}-${RELAY_MAX}"
echo
echo "自检（本机）："
echo "  ss -ulnp | grep 3478 || netstat -ulnp | grep 3478"
echo "  journalctl -u coturn -n 30 --no-pager   # 或 turnserver"
echo
echo "信令侧确认 ICE 已带 turn（重启 signal 后新建房间再连）："
echo "  手机/浏览器 WebRTC 日志应出现 relay 候选（对称 NAT / 蜂窝时）"
echo "=============================="
